<?php

/**
 * Enqueue theme assets.
 *
 * @package Blank-Theme-Child
 */

namespace Blank_Theme_Child\Inc;

use Blank_Theme_Child\Inc\Traits\Singleton;

/**
 * Class Assets
 */
class Assets
{

	use Singleton;

	/**
	 * Construct method.
	 *
	 * Initializes the class and sets up necessary hooks.
	 */
	protected function __construct()
	{
		// Set up hooks for the class
		$this->setup_hooks();
	}

	/**
	 * Set up hooks for the class.
	 *
	 * This method sets up necessary hooks for the class, such as registering
	 * scripts and styles to be enqueued.
	 *
	 * @return void
	 */
	protected function setup_hooks()
	{
		// Register and enqueue scripts and styles.
		add_action('wp_enqueue_scripts', [$this, 'register_assets']);
	}

	/**
	 * Register and enqueue theme assets.
	 *
	 * This method registers and enqueues all assets for the theme.
	 *
	 * @return void
	 */
	public function register_assets()
	{
		$this->register_styles();
		$this->register_scripts();
	}

	/**
	 * Register and enqueue theme scripts.
	 *
	 * This method registers the main JavaScript file for the theme and enqueues
	 * it to be included in the front-end. It includes necessary dependencies
	 * such as jQuery.
	 *
	 * @return void
	 */
	public function register_scripts()
	{
		// Register the main JavaScript file for the theme with jQuery dependency.
		$this->register_script('blank-theme-child-main', 'js/main.js', ['jquery']);

		// Enqueue the registered JavaScript file to be included in the front-end.
		wp_enqueue_script('blank-theme-child-main');
	}

	/**
	 * Register and enqueue styles for the theme.
	 *
	 * This method registers the main CSS file for the theme and enqueues it
	 * to be included in the front-end of the site.
	 *
	 * @return void
	 */
	public function register_styles()
	{
		// Register the main CSS file for the theme.
		$this->register_style('blank-theme-child-main', 'css/main.css', ['parent-template-theme-css']);

		// Enqueue the registered CSS file to be included in the front-end.
		wp_enqueue_style('blank-theme-child-main');
	}

	/**
	 * Retrieves asset dependencies and version info from {handle}.asset.php if exists.
	 *
	 * This method reads the asset meta data from the asset.php file if it exists.
	 * The asset.php file is generated by the build process and contains information
	 * about the dependencies and version of the asset.
	 *
	 * @param string $file File name.
	 * @param array  $deps Script dependencies to merge with.
	 * @param string $ver  Asset version string.
	 *
	 * @return array {
	 *     Array of asset dependencies and version.
	 *
	 *     @type array  $dependencies Array of registered script handles this script depends on.
	 *     @type string $version      String specifying script version number.
	 * }
	 */
	public function get_asset_meta($file, $deps = [], $ver = false)
	{
		$asset_meta = [
			'dependencies' => [],
			'version'      => $this->get_file_version($file, $ver),
		];

		// Determine file extension for asset meta lookup
		$file_extension = pathinfo($file, PATHINFO_EXTENSION);
		$file_name      = basename($file, '.' . $file_extension);

		// Set appropriate directory based on file type
		$directory = ('css' === $file_extension) ? 'css' : 'js';

		// Get the asset meta file path.
		$asset_meta_file = sprintf(
			'%s/%s/%s.asset.php',
			untrailingslashit(BLANK_THEME_CHILD_BUILD_DIR),
			$directory,
			$file_name
		);

		// If the file is readable, read the asset meta data from the file.
		if (is_readable($asset_meta_file)) {
			$file_meta = require $asset_meta_file;

			if (isset($file_meta['dependencies']) && is_array($file_meta['dependencies'])) {
				$asset_meta['dependencies'] = $file_meta['dependencies'];
			}

			if (isset($file_meta['version'])) {
				$asset_meta['version'] = $file_meta['version'];
			}
		}

		// Merge with provided dependencies.
		if (! empty($deps) && is_array($deps)) {
			$asset_meta['dependencies'] = array_unique(
				array_merge($asset_meta['dependencies'], $deps)
			);
		}

		// Return the asset meta data.
		return $asset_meta;
	}

	/**
	 * Register a new script.
	 *
	 * This method registers a new script with the WordPress script enqueueing API.
	 *
	 * @param string           $handle    Name of the script. Should be unique.
	 * @param string           $file      Script file, path of the script relative to the assets/build/ directory.
	 * @param array            $deps      Optional. An array of registered script handles this script depends on. Default empty array.
	 * @param string|bool|null $ver       Optional. String specifying script version number, if not set, filetime will be used as version number.
	 * @param bool             $in_footer Optional. Whether to enqueue the script before </body> instead of in the <head>. Default true.
	 * 
	 * @return bool Whether the script has been registered. True on success, false on failure.
	 */
	public function register_script($handle, $file, $deps = [], $ver = false, $in_footer = true)
	{
		// Get the URL of the script file.
		$src = sprintf('%s/%s', BLANK_THEME_CHILD_BUILD_URI, $file);

		// Get the asset meta data.
		$asset_meta = $this->get_asset_meta($file, $deps, $ver);

		// Register the script with the WordPress script enqueueing API.
		return wp_register_script(
			$handle,
			$src,
			$asset_meta['dependencies'],
			$asset_meta['version'],
			$in_footer
		);
	}

	/**
	 * Register a CSS stylesheet.
	 *
	 * Registers a CSS stylesheet with WordPress.
	 *
	 * @param string           $handle Name of the stylesheet. Should be unique.
	 * @param string           $file   Style file, path of the script relative to the assets/build/ directory.
	 * @param array            $deps   Optional. An array of registered stylesheet handles this stylesheet depends on.
	 *                                 Default empty array.
	 * @param string|bool|null $ver    Optional. String specifying script version number.
	 *                                 If not set, filetime will be used as version number.
	 * @param string           $media  Optional. The media for which this stylesheet has been defined.
	 *                                 Default 'all'. Accepts media types like 'all', 'print' and 'screen', or media queries like
	 *                                 '(orientation: portrait)' and '(max-width: 640px)'.
	 *
	 * @return bool Whether the style has been registered. True on success, false on failure.
	 */
	public function register_style($handle, $file, $deps = [], $ver = false, $media = 'all')
	{
		// Get the URL of the style file.
		$src = sprintf('%s/%s', BLANK_THEME_CHILD_BUILD_URI, $file);

		// Get the asset meta data.
		$asset_meta = $this->get_asset_meta($file, $deps, $ver);

		// Register the style with the WordPress script enqueueing API.
		return wp_register_style(
			$handle,
			$src,
			$asset_meta['dependencies'],
			$asset_meta['version'],
			$media
		);
	}

	/**
	 * Get file version.
	 *
	 * Retrieves a file version. If the $ver parameter is provided, it returns that version.
	 * If the $ver parameter is not provided, it attempts to retrieve the modification time of the file.
	 * If the file does not exist, it returns false.
	 *
	 * @param string             $file File path.
	 * @param string|int|boolean $ver  File version.
	 *
	 * @return string|int|boolean
	 */
	public function get_file_version($file, $ver = false)
	{
		// If a version is provided, return it.
		if (! empty($ver)) {
			return $ver;
		}

		// Get the file path.
		$file_path = sprintf('%s/%s', BLANK_THEME_CHILD_BUILD_DIR, $file);

		// Check if the file exists.
		if (file_exists($file_path)) {
			// If the file exists, get the modification time.
			return filemtime($file_path);
		}

		// If the file does not exist or no version specified, use theme version.
		return defined('BLANK_THEME_CHILD_VERSION') ? BLANK_THEME_CHILD_VERSION : '1.0.0';
	}
}
